# Generated by Django 3.0.5 on 2020-04-15 14:07
from django.db import migrations, models
from faker import Faker
import random


def add_data(apps, schema_editor):
    f = Faker(['ru_RU'])
    Faker.seed(0)
    human = apps.get_model('human', 'Human')
    match = apps.get_model('match', 'Match')
    for i in range(0, 10):
        rand = random.randint(1, 2)
        data = {
            "first_name": f.first_name_male() if rand == 1 else f.first_name_female(),
            "second_name": f.last_name_male() if rand == 1 else f.last_name_female(),
            "age": random.randint(16, 80),
            "gender": "M" if rand == 1 else "F"
        }
        h = human.objects.create(**data)
        match.objects.create(human_id=h.id, **data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
