# Generated by Django 3.0.5 on 2020-04-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
        ('human', '0002_auto_20200415_1917'),
    ]

    operations = [
    ]
